/**
 * Verify ED25519 message signature generated by Albedo signer app.
 * @param {String} publicKey - Ed25519 public key in StrKey encoding ("GDWP...N4LO").
 * @param {String} message - Arbitrary text message signed by the given public key.
 * @param {String|Buffer|Uint8Array} signature - Hex-encoded message signature.
 * @return {Boolean} - Returns true if a signature is valid and false otherwise.
 */
export function verifyMessageSignature(publicKey: string, message: string, signature: string | Buffer | Uint8Array): boolean
